### ISSUE TITLE
Can we get rid of or merge this repo?

### ISSUE THREAD

**Issue by danielhertenstein** [mozilla/fathom-trainees#8]
Does fathom-trainees need to exist as a separate repo or even as an addon? It's primary purpose is to make a ruleset available to FathomFox and then provide hooks to Fathom to evaluate the ruleset.

Can his functionality be pulled into FathomFox? Can a user simply give a ruleset to FathomFox in some way and FathomFox makes the calls to Fathom?

**Comment by biancadanforth** [comment]
Thanks @danielhertenstein for filing this issue. I brought this up with Erik again in our last 1:1 as I have been working on developing the Articles ruleset for the Smoot project.

As I see it, there are a number of benefits to doing this.
* For developers, they would no longer have to:
  * Clone the `fathom-trainees` repo (granted they'd clone FathomFox instead)
  * Manually install `FathomFox` from AMO after starting up the extension from the command line via `yarn run browser`.
  * Link the `trainees.js` file (and any dependencies) to the same files in the `fathom-trainees/src` folder each time it (or any of its dependencies) is modified (granted they'd link this in FathomFox instead).[1]
* For the core Fathom team, we would no longer have to:
  * Use message passing between FathomFox and the `fathom-trainees` extension; simple is always better.
  * Maintain an additional Fathom-related repo, which makes it harder to track interdependent issues like this one.

Paraphrasing @erikrose ...
On why fathom-trainees exists in the first place:
> 1. It all came down to wanting to put the ruleset into version control. If we went with a single WebExtension (FathomFox with the ruleset embedded), obviously you end up maintaining your own fork of FathomFox.
>  * This is solved by symlinks, if you’re on a platform that uses symlinks. Are symlinks an issue on Windows?
> 2. Secondarily, Fathom Fox uses `rollup`. Maybe a Fathom project like Price Wise wanted to use `webpack` to stick together their ruleset.

On downsides to merging `fathom-trainees` into `fathom-fox`:
> * The only downside I can think of is you really can’t use FathomFox on AMO for anything other than Corpus Collection. Training features like using the Vectorizer would require building FathomFox on the command line.

On what changes technically would we have to do?
> * Replace any message passing of the `trainees` object with an `import` statement. These places can be found easily by grepping for the addon id, `"fathomtrainees@mozilla.com"`.
> * Use a symlink in FathomFox to reference the Fathom ruleset to use.

[1]: One idea for this particular issue is to hard link the files in `fathom-trainees/src` to the source files (e.g. `trainees.js`) in the project repo. I spent a couple hours today trying to get that working, but `rollup` doesn't detect the file change events despite the contents and the date modified value changing for the linked file.

**Comment by erikrose** [comment]
I'm sympathetic to the idea.

### Pros:
* 1 extension. 1 call to web-ext. No AMO twiddling for the ruleset author.
* Encourages people to version their rulesets with their corpora

### To do:
* Ship FathomFox with a blankish, example, commented-out ruleset.
* Rewrite a bunch of docs in Fathom and FathomFox.

### Still to figure out:
How do we relieve ruleset authors of having to become rollup experts? trainees.js is always going to need a build step to make its imports from Fathom (`ruleset`, `rule`, `type`, etc.) work. The simplest thing—and possibly a good way for a rank beginner to start—is to have FathomFox's rollup config go ahead and compile trainees.js. I think we should at least do that.

Actually, that's probably enough forever. I just tried the hardlink trick, and it works great. (@biancadanforth, I can help you troubleshoot your setup.) Authors can stick the trainees.js in their own project (versioning it with their corpus), hardlink it into FathomFox, and away they go. No rollup.config or package.json dependency lines to document and spread around.

This seems too easy. What are we missing? :-)

**Comment by biancadanforth** [comment]
>  I just tried the hardlink trick, and it works great. (@biancadanforth, I can help you troubleshoot your setup.)

It works fine as long as the file is a top level file in the bundle. `rollup -w` doesn't detect change events if you update a file that is `import`ed by a top level file.

This would be a common scenario, as the ruleset needs to be used both for training and the application (e.g. Price Tracker), so it makes sense to keep that as a separate file.

**Comment by erikrose** [comment]
I ran `yarn run watch` in the top-level, but changed src/contentScript.js, so it's not a top-level thing—perhaps it's rather that rollup watching doesn't follow imports (which I wouldn't expect it to).

**Comment by biancadanforth** [comment]
(Note: This comment is a deep dive into one of the points made above about hardlinking the `trainees.js` file and its dependencies; if you're interested in the main issue here, please skip this comment.)
> I just tried the hardlink trick, and it works great.

I was not having as good of luck, but I had a chat with @mythmon, and he helped me figure out the complicated root cause at least for why it wasn't working for me:

**Steps to Reproduce**
1. You have a `trainees.js` file in your project directory that may or may not have some `import` statements.
2. You have a `fathom-trainees` fork that you have not yet modified (`master` at cb856e5), and you have run `yarn install`. I.e. a `git status` is clean.
3. Create a hardlink between your project’s `trainees.js` and `fathom-trainees`’s `trainees.js`. E.g.:
```
ln -f ~/Projects/fathom-smoot/articles/trainees.js ~/Projects/fathom-trainees/src
```
4. Make sure when you open fathom-trainees/src/trainees.js that it now matches your projects `trainees.js` file exactly.
5. If your `trainees.js` file has any imports, create a hardlink between the file in your project to the same relative path in the `fathom-trainees` repo. E.g.
```
ln -f ~/Projects/fathom-smoot/articles/file.js ~/Projects/fathom-trainees/src
```
6. In the fathom-trainees root directory, `yarn run watch`
7. While watching that terminal window, make a change to `trainees.js`.

Expected results:
The terminal indicates that fathom-trainees has been rebuilt after detecting a change.
Actual results:
There is no change in the terminal, and the bundled fathom-trainees (in fathom-trainees/addon) has not changed.

**Root cause**
* Based on [`rollup`'s documentation](https://rollupjs.org/guide/en/#big-list-of-options) (search for "Watch options"), it claims it defaults to Node's [`fs.watch`](https://nodejs.org/api/fs.html#fs_fs_watch_filename_options_listener) to watch files on `rollup --watch`, but that you can specify to use a separate node package, [`chokidar`](https://github.com/paulmillr/chokidar), instead via the command line, noting that you have to install `chokidar` separately.
* In reality, based on [`rollup`’s source code](https://github.com/rollup/rollup/blob/master/src/watch/fileWatchers.ts#L83), `rollup` checks if `chokidar` is installed. If it’s there, `rollup` uses it even if we don’t explicitly specify to use it. (Thankfully, there is an option to explicitly specify _not_ to use it; more on that in a bit.)
* If we deleted the `node_modules` folder and did a clean `yarn install`, what we discovered was that `chokidar` was somehow installed!

In terminal:
```bash
rm -rf node_modules
yarn install
node
```
In Node REPL:
```js
require.resolve(‘chokidar’) // '/Users/bdanforth/Projects/fathom-trainees/node_modules/chokidar/index.js'
```
* How was it getting installed? We can check `yarn why chokidar` to discover the truth: `chokidar` is a nested dep of `web-ext`, a `devDep` for `fathom-trainees`.
* Since `rollup` was detecting that `chokidar` was installed, it was using `chokidar`'s default method of watching files.
* When we looked at `chokidar`’s file watching, we found that it used [two different options](https://github.com/paulmillr/chokidar/blob/master/index.js#L13-L14): Node’s `fs.watch` or `FsEvents`. For MacOS, [it uses `FSEvents` by default](https://github.com/paulmillr/chokidar/blob/master/index.js#L310).
* For whatever reason on MacOS at least, listening for file change events through `FsEvents` does not detect a file change event for the hard link (perhaps it is checking for direct writes only, not whether the content of the file changes?), while listening via Node's `fs.watch` does.
* We noticed if we set the `rollup.config.js` option to add `watch.chokidar.useFsEvents` = `false` that `yarn run watch` did work with the hard link.
* So if `chokidar` falls back to `fs.watch`, it works.  Since `rollup` will use Node's `fs.watch` method by default if `chokidar` is not installed, what we need to do is explicitly tell `rollup` _not_ to use `chokidar`, since we do happen to have it installed thanks to `web-ext`.
  * i.e. `yarn rollup -c --no-watch.chokidar`.
  * Alternatively, we can modify the `rollup.config.js` file to specify `watcher.chokidar: false`.
In the end, the solution is a simple three-line change in `rollup.config.js`:
```diff
diff --git a/rollup.config.js b/rollup.config.js
index 3056518..d056574 100644
--- a/rollup.config.js
+++ b/rollup.config.js
@@ -25,7 +25,10 @@ function mindlesslyFactoredOutSettings(name) {
             json(),
             globals(),
             builtins()
-        ]
+        ],
+        watch: {
+            chokidar: false
+        }
     }
 }
```

**Comment by erikrose** [comment]
Even if the user's trainees.js has 3rd-party dependencies, it still shouldn't be a problem. Rather than modifying FathomFox's package.json, they should keep track of all that in _their_ repo, let _their_ build process resolve and inline those dependencies, and then link the _built_ trainees.js into FathomFox. Users without the need for third-party deps can just let FathomFox's build process take care of things.
